Note: Environment variable`HF_TOKEN` is set and is the current active token independently from the token you've just configured.
Connecting to LLM Model...
LLM Model Connected
Connecting to Vision Model...
Vision Model Connected
Processing items from index 80 to 100
Processing item 80
Error processing item 80: 429 Resource has been exhausted (e.g. check quota).
Processing item 81
Error processing item 81: 429 Resource has been exhausted (e.g. check quota).
Processing item 82
Error processing item 82: 429 Resource has been exhausted (e.g. check quota).
Processing item 83
Error processing item 83: 429 Resource has been exhausted (e.g. check quota).
Processing item 84
Error processing item 84: 429 Resource has been exhausted (e.g. check quota).
Processing item 85
Error processing item 85: '1459106'
Processing item 86
Processing item 87
Error processing item 87: 429 Resource has been exhausted (e.g. check quota).
Processing item 88
Error processing item 88: 429 Resource has been exhausted (e.g. check quota).
Processing item 89
Error processing item 89: 429 Resource has been exhausted (e.g. check quota).
Processing item 90
Traceback (most recent call last):
  File "F:\Thesis\DKH-Thesis\src\inference_use_searched_evidences.py", line 283, in <module>
    main()
  File "F:\Thesis\DKH-Thesis\src\inference_use_searched_evidences.py", line 242, in main
    result = inference(
  File "F:\Thesis\DKH-Thesis\src\inference_use_searched_evidences.py", line 102, in inference
    internal_result = llm_connector.call_with_structured_output(
  File "F:\Thesis\DKH-Thesis\src\modules\reasoning_module\connector\gemini.py", line 69, in call_with_structured_output
    res = self.model.generate_content(
  File "F:\Thesis\DKH-Thesis\venv\lib\site-packages\google\generativeai\generative_models.py", line 331, in generate_content
    response = self._client.generate_content(
  File "F:\Thesis\DKH-Thesis\venv\lib\site-packages\google\ai\generativelanguage_v1beta\services\generative_service\client.py", line 830, in generate_content
    response = rpc(
  File "F:\Thesis\DKH-Thesis\venv\lib\site-packages\google\api_core\gapic_v1\method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
  File "F:\Thesis\DKH-Thesis\venv\lib\site-packages\google\api_core\retry\retry_unary.py", line 293, in retry_wrapped_func
    return retry_target(
  File "F:\Thesis\DKH-Thesis\venv\lib\site-packages\google\api_core\retry\retry_unary.py", line 144, in retry_target
    result = target()
  File "F:\Thesis\DKH-Thesis\venv\lib\site-packages\google\api_core\timeout.py", line 120, in func_with_timeout
    return func(*args, **kwargs)
  File "F:\Thesis\DKH-Thesis\venv\lib\site-packages\google\api_core\grpc_helpers.py", line 76, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "F:\Thesis\DKH-Thesis\venv\lib\site-packages\grpc\_channel.py", line 1178, in __call__
    ) = self._blocking(
  File "F:\Thesis\DKH-Thesis\venv\lib\site-packages\grpc\_channel.py", line 1162, in _blocking
    event = call.next_event()
  File "src\\python\\grpcio\\grpc\\_cython\\_cygrpc/channel.pyx.pxi", line 388, in grpc._cython.cygrpc.SegregatedCall.next_event
  File "src\\python\\grpcio\\grpc\\_cython\\_cygrpc/channel.pyx.pxi", line 211, in grpc._cython.cygrpc._next_call_event
  File "src\\python\\grpcio\\grpc\\_cython\\_cygrpc/channel.pyx.pxi", line 205, in grpc._cython.cygrpc._next_call_event
  File "src\\python\\grpcio\\grpc\\_cython\\_cygrpc/completion_queue.pyx.pxi", line 78, in grpc._cython.cygrpc._latent_event
  File "src\\python\\grpcio\\grpc\\_cython\\_cygrpc/completion_queue.pyx.pxi", line 61, in grpc._cython.cygrpc._internal_latent_event
  File "src\\python\\grpcio\\grpc\\_cython\\_cygrpc/completion_queue.pyx.pxi", line 42, in grpc._cython.cygrpc._next
KeyboardInterrupt
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1740155938.631799  194096 init.cc:229] grpc_wait_for_shutdown_with_timeout() timed out.
